### PR TITLE
Convert to noarch package

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #3 
Fixes #2

### CODE REVIEW

**Comment by johannesring** [comment]
It looks like this failed to build on CircleCI after it was merged (https://circleci.com/gh/conda-forge/sphinxjp.themes.impressjs-feedstock/11) and I don't seem to have permission to restart the build. @conda-forge-admin - can you help me out here?

**Comment by xhochy** [comment]
@conda-forge-admin please update circle

**Comment by xhochy** [comment]
@conda-forge/core Can someone restart the above (failed) circle build now that the token was updated?

**Comment by scopatz** [comment]
restarted

**Pull request merged**
